/* tslint:disable */
/* eslint-disable */
/**
 * APISIX Admin API
 * APISIX Admin API is a RESTful API that allows you to create and manage APISIX resources.
 *
 * The version of the OpenAPI document: 3.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

